name: Bun CI

on:
  release:
    types: [created]
  #pull_request:
   #branches: [ "main" ]

permissions:
  contents: write
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
    - run: bun install --frozen-lockfile
    - run: bun run build
    - run: echo > dist/.nojekyll
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: dist
